### ISSUE TITLE
Update the vision pi

### ISSUE THREAD

**Issue by youngcm2** [mattkrafft/prestigecalc#1]
Here is the screenshot for the vision 5/50 dupe 40 PI.
![img_2131](https://cloud.githubusercontent.com/assets/862338/15307753/e55d189c-1b9b-11e6-9f67-8ff242723f27.jpg)

**Comment by mattkrafft** [comment]
Nice, I noticed this today, TVision was ahead of drax on an alliance mates profile, but not on my calc for him.  I knew there was an issue.

**Comment by youngcm2** [comment]
They updated the PI for both the vision and classic vision.

**Comment by mattkrafft** [comment]
I got the 99 value from the Russian website, is this cap of your profile or do you have a collection of them?

**Comment by youngcm2** [comment]
That is directly from the member feed which shows prestige.
