### ISSUE TITLE
Add new standard 5* champs 

### ISSUE THREAD

**Issue by Thunderr** [mattkrafft/prestigecalc#3]
About a month before the magneto, hawkeye, antman, war machine, drax and iron fist has been added to 5\* crystal. Could you add them to your table?

Thanks

**Comment by mattkrafft** [comment]
in order to add the new 5 star heroes to the sheet I need in game data on them.  I cant characterize a 5 star without at least 3 data points above sig level 0.  When these heroes creep into peoples top 5, and start impacting their prestige, we can start getting accurate data.
